### ISSUE TITLE
Conflicts with uBlock Origin (was: Doesn't work on Nightly.)

### ISSUE THREAD

**Issue by streetwolf** [Treora/selector-extension#2] opened 2017-05-29 12:34 UTC
Seems the link doesn't make it into the clipboard therefore there is nothing to paste.

**Comment by Treora** [comment] 2017-05-29 15:53
Thanks for reporting! I just installed Nightly 55.0a1 (2017-05-28) (64-bit) on Ubuntu, and it works fine however. Unfortunately I do not know why it does not work for you. Just for clarity, the normal copy is not changed, you have to use the 'copy link to selected text' option from the context menu.

I'd be glad to hear if it persists or if more people have this problem, and whether perhaps any errors are reported on the console. If you or anyone with the issue feels like investigating, a simple thing to test is whether a normal copy is executed (does the text end up in the clipboard). With more effort, in the debugger these things could be tested (a bit of a hassle as code is transpiled&browserified):
 - Is the context menu [listener](https://github.com/Treora/precise-links/blob/501e3258333ea493eef9492fa525792dbb494658/src/background_script.js#L11) triggered in the background script?
- Does the content script [receive](https://github.com/Treora/precise-links/blob/501e3258333ea493eef9492fa525792dbb494658/src/reference.js#L40) the message from background script?
- Is the copy [event handler](https://github.com/Treora/precise-links/blob/501e3258333ea493eef9492fa525792dbb494658/src/reference.js#L33) invoked?

**Comment by streetwolf** [comment] 2017-05-29 16:44
UPDATE

I must have been using your add-on incorrectly.  It works on sites within forum posts.  It works on sites like Github.  My original test was highlighting some text on cnn.com.  Before it didn’t copy anything to the clipboard now it does.  However all I get selecting text from a news article is what I highlighted not a link.  Is this the expected behavior?
____
Gary

**Comment by streetwolf** [comment] 2017-05-29 16:49
Selecting text in a cnn article just produces the text I highlighted instead of the link.  However, at a site like msn.com selecting a news article text does produce a link to the selected text.  Apparently your add-on doesn’t work on all sites.

____
Gary

**Comment by Treora** [comment] 2017-05-29 17:11
In a quick test it also worked on articles on msn.com and cnn.com for me. There could however be undiscovered problems with some websites or situations. Also some links may created fine, but the extension might not be able to correctly find the specified text again. It's experimental. :)

I'll close this issue, but feel free to report again if you find specific and reproducable problems.

**Closed as completed by Treora** 2017-05-29 17:11 UTC

**Comment by streetwolf** [comment] 2017-05-29 17:19
Does this work for you?

Go to
http://www.cnn.com/2017/05/29/opinions/withdraw-paris-accord-opinion-cruz/index.html

Scroll down a few paragraphs in the article.

Select some text.  Paste it somewhere like the search box.  I have just the text not a link.  How about you?

I’ve also found that on some sites I have to select the right text in order to get a link.

Also sites like
http://archive.mozilla.org/pub/firefox/tinderbox-builds/mozilla-inbound-win64-pgo/
http://archive.mozilla.org/pub/firefox/tinderbox-builds/mozilla-inbound-win64-pgo/
only send me to the top of the page even if I select text farther down into the list.


____
Gary

**Comment by streetwolf** [comment] 2017-05-29 17:35
I found out the problem.  Your add-on appears to have a conflict with uBlock Origin at least at cnn.com.  When I disable uBO for cnn your add-on works fine.  I suspect uBO also affects other sites I am having problems on.  Don’t know if it’s a rule or uBO itself.  Since it works at some other sites it’s probably a rule.

I am using a beta version of uBO found here:
 <a href="https://github.com/gorhill/uBlock/releases/download/1.12.5b16/uBlock0.webext.xpi" title="1.71 MB uBlock0.webext.xpi">1.71 MB uBlock0.webext.xpi</a>

____
Gary

**Comment by streetwolf** [comment] 2017-05-29 19:07
I’m running under Windows 10 64-bit.  I do get the context menu entry.  I opened up my browser log and each time after I select some text and click on your menu entry this appears in the log:

Error: Could not establish connection. Receiving end does not exist.

____
Gary

**Comment by Treora** [comment] 2017-05-30 15:48
Ok, I don't know how exactly uBlock Origin interferes, but good you found the cause. I don't think I'll investigate this, but I'll update the issue title; it would be great if you update the title of your review on AMO as well. :)
